
project:
  name: start

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zjmall-product
    username: root
    password: 123abcABC


